/** @file
 * Common data structures and definitions for Proxy Verifier tools.
 *
 * Copyright 2021, Verizon Media
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#include "http.h"

#include <chrono>
#include <deque>
#include <list>
#include <memory>
#include <ngtcp2/ngtcp2.h>
#include <nghttp3/nghttp3.h>
#include <openssl/ssl.h>
#include <random>
#include <string>
#include <unordered_map>
#include <vector>

#include "swoc/BufferWriter.h"
#include "swoc/Errata.h"
#include "swoc/MemArena.h"
#include "swoc/swoc_ip.h"
#include "swoc/TextView.h"

class HttpHeader;
struct Txn;

namespace swoc
{
inline namespace SWOC_VERSION_NS
{
namespace bwf
{
/** Format wrapper for @c ngtcp2 errors.
 */
struct Ngtcp2Error
{
  int _e;
  explicit Ngtcp2Error(int e) : _e(e) { }
};

/** Format wrapper for @c nghttp3 errors.
 */
struct Nghttp3Error
{
  int _e;
  explicit Nghttp3Error(int e) : _e(e) { }
};
} // namespace bwf

BufferWriter &bwformat(BufferWriter &w, bwf::Spec const &spec, bwf::Ngtcp2Error const &error);
BufferWriter &bwformat(BufferWriter &w, bwf::Spec const &spec, bwf::Nghttp3Error const &error);
} // namespace SWOC_VERSION_NS
} // namespace swoc

/** Encapsulate the buffer for the QUIC TLS hanshake. */
class QuicHandshake
{
public:
  QuicHandshake();
  ~QuicHandshake() = default;

  QuicHandshake(QuicHandshake const &) = delete;
  QuicHandshake &operator=(QuicHandshake const &) = delete;

public:
  std::vector<char> buf;

  /** This is the maximum number of bytes we expect to use for the TLS
   * handshake.
   *
   * This max value is taken from CURL code which has a comment expressing
   * tentative hope that this should be large enough. There is an assertion in
   * our (and theirs, I believe) implementation guarding this invariant. If we
   * trip that, we may need to expand this.
   */
  static constexpr size_t max_handshake_size = 4 * 1024;
};

// TODO: this is copied from curl's ngtcp2.h. That is a c file. Refactor using
// C++ principles.
//
// TODO: I suspect that these will get wrapped up into H3StreamState and H3Session.
class QuicSocket
{
public:
  // The following is a massive curl structure containing data about the
  // connection. Clearly it won't be used and populated by us, but we'll need
  // to figure out how to replace its functionality.
  //
  // Looking at the code, this all seems pretty curl specific and should not be
  // needed by us. Hopefully we can cut it all out pretty easily.
  // struct connectdata *conn = nullptr; /* point back to the connection */

  QuicSocket();
  ~QuicSocket();

  QuicSocket(QuicSocket const &) = delete;
  QuicSocket &operator=(QuicSocket const &) = delete;

  static void randomly_populate_array(uint8_t *array, size_t array_len);

public:
  ngtcp2_conn *qconn = nullptr;
  ngtcp2_cid dcid;
  ngtcp2_cid scid;
  uint32_t version = 0;
  ngtcp2_settings settings;
  ngtcp2_transport_params transport_params;
  SSL_CTX *sslctx = nullptr;
  SSL *ssl = nullptr;
  /// 3 is the maximum enum value in ngtcp2_crypto_level.
  static constexpr int MAX_NGTCP2_CRYPTO_LEVEL = 3;
  QuicHandshake crypto_data[MAX_NGTCP2_CRYPTO_LEVEL];
  /* the last TLS alert description generated by the local endpoint */
  uint8_t tls_alert = 0;
  struct sockaddr_storage local_addr;
  socklen_t local_addrlen = 0;

  nghttp3_conn *h3conn = nullptr;
  nghttp3_settings h3settings;
  int qlogfd = 0;

private:
  // Members to support random number generation for connection id.
  static std::random_device rd;
  static std::mt19937 rng;
  static std::uniform_int_distribution<int> uni_id;
};

class H3StreamState
{
public:
  /**
   * @param[in] is_client Whether this stream state is for a client. That is,
   * is this stream state functioning as a client that will send a request, or
   * a server receiving a request.
   */
  H3StreamState(bool is_client);
  ~H3StreamState();

  /// Set the stream_id for this and the appropriate members.
  void set_stream_id(int64_t stream_id);

  /// Retrieve the stream id for this stream.
  int64_t get_stream_id() const;

  /** Increment the nghttp3 reference count on buf and return a view of it.
   *
   * A reference count to the buffer will be held for the remainder of the
   * lifetime of the stream.
   *
   * @param[in] buf The nghttp3 ref counted buffer to register and for which a
   * TextView will be returned.
   *
   * @return A view representation of the given buffer.
   */
  swoc::TextView register_rcbuf(nghttp3_rcbuf *rcbuf);

public:
  /// The key identifying this HTTP transaction.
  std::string key;

  /** The composed URL parts from :method, :authority, and :path pseudo headers
   * from the request.
   *
   * This is stored in this object to persist its storage because parse_url
   * assigns from this string TextViews.
   */
  std::string composed_url;

  /// This is state is for a server receiving a request from a client.
  bool will_receive_request = false;

  /// This is state is for a client receiving a response from a server.
  bool will_receive_response = false;

  /// Headers have been received from the peer.
  bool have_received_headers = false;

  std::chrono::time_point<std::chrono::system_clock> stream_start;
  /// The HTTP request headers for this stream.
  std::shared_ptr<HttpHeader> request_from_client;
  /// The HTTP response headers for this stream.
  std::shared_ptr<HttpHeader> response_from_server;

  HttpHeader const *specified_response = nullptr;

  char const *body_to_send = nullptr;
  size_t send_body_length = 0;
  // TODO: see comment in cb_h3_readfunction. We may not need offset in the
  // end, but leaving it for here now.
  size_t send_body_offset = 0;

  /** For requests, whether this requests is waiting for a 100 Continue
   * response. */
  bool wait_for_continue = false;

private:
  /** The QUIC stream ID for this stream. */
  int64_t _stream_id;
  std::deque<nghttp3_rcbuf *> _rcbufs_to_free;
};

class H3Session : public Session
{
public:
  using super_type = Session;
  H3Session();
  H3Session(swoc::TextView const &client_sni, int client_verify_mode = SSL_VERIFY_NONE);
  ~H3Session();
  swoc::Rv<ssize_t> read(swoc::MemSpan<char> span) override;
  swoc::Rv<ssize_t> write(swoc::TextView data) override;
  swoc::Rv<ssize_t> write(HttpHeader const &hdr) override;

  swoc::Errata pack_headers(HttpHeader const &hdr, nghttp3_nv *&nv_hdr, int &hdr_count);

  /** For HTTP/3, we read on the socket until an entire stream is done.
   *
   * For HTTP/1, we first read headers to get the Content-Length or other
   * header information to direct reading the body. For HTTP/3, this isn't
   * an issue because bodies are explicitly framed.
   */
  swoc::Rv<int> poll_for_headers(std::chrono::milliseconds timeout) override;
  swoc::Rv<std::shared_ptr<HttpHeader>> read_and_parse_request(swoc::FixedBufferWriter &w) override;
  swoc::Rv<size_t> drain_body(
      HttpHeader const &hdr,
      size_t expected_content_size,
      swoc::TextView bytes_read) override;

  /** Perform the server-side QUIC TLS handshake for a connection. */
  swoc::Errata accept() override;

  /** Perform the client-side QUIC TLS handshake for a connection. */
  swoc::Errata connect() override;
  // TODO: rename from real_target.
  swoc::Errata do_connect(swoc::IPEndpoint const *real_target) override;

  static swoc::Errata init(int *process_exit_code);

  /** Indicates that that the user should receive a non-zero status code.
   *
   * Most of this code is blocking a procedural and this can be communicated to
   * the caller via Errata. But the HTTP/2 nghttp2 callbacks do not return
   * directly to a caller. Therefore this is used to communicate a non-zero
   * status.
   */
  static void set_non_zero_exit_status();


  /** Perform the HTTP/3 (ngtcp2 and nghttp3) configuration for a client
   * connection. */
  swoc::Errata client_session_init();

  /** Perform the HTTP/3 (ngtcp2 and nghttp3) configuration for a server
   * connection. */
  swoc::Errata server_session_init();
  swoc::Errata send_connection_settings();
  static void terminate();
  swoc::Errata run_transactions(
      std::list<Txn> const &txn,
      swoc::IPEndpoint const *real_target,
      double rate_multiplier) override;
  swoc::Errata run_transaction(Txn const &txn) override;

  /** Indicate that the stream has ended (received the END_STREAM flag).
   *
   * @param[in] stream_id The stream identifier for which the end stream has
   * been processed.
   */
  void set_stream_has_ended(int64_t stream_id);

  /// Whether an entire stream has been received and is ready for processing.
  bool get_a_stream_has_ended() const;

  void record_stream_state(int64_t stream_id, std::shared_ptr<H3StreamState> stream_state);

public:
  /// A mapping from stream_id to H3StreamState.
  std::unordered_map<int64_t, std::shared_ptr<H3StreamState>> _stream_map;
  QuicSocket _quic_socket;

protected:
  static swoc::Errata client_init(SSL_CTX *&client_context);
  static swoc::Errata server_init(SSL_CTX *&server_context);
  static void terminate(SSL_CTX *&client_context);

protected:
  /** The SNI to be sent by the client (as opposed to the one expected by the
   * server from the proxy). This only applies to the client.
   */
  std::string _client_sni;

  /** The verify mode for the client in the TLS handshake with the proxy.
   * This only applies to the client.
   */
  int _client_verify_mode = SSL_VERIFY_NONE;

  SSL *_ssl = nullptr;

private:
  nghttp3_nv tv_to_nv(char const *name, swoc::TextView v);
  swoc::Errata connect_udp_socket(swoc::IPEndpoint const *real_target);
  int quic_init_ssl(std::string const &hostname);
  void receive_responses();

private:
  std::deque<int64_t> _ended_streams;
  swoc::IPEndpoint const *_endpoint = nullptr;

  std::shared_ptr<H3StreamState> _last_added_stream;

#ifndef OPENSSL_NO_NEXTPROTONEG
  static unsigned char next_proto_list[256];
  static size_t next_proto_list_len;
#endif /* !OPENSSL_NO_NEXTPROTONEG */

  /** The client context to use for HTTP/3 connections.
   *
   * This is used per HTTP/3 connection so that ALPN advertises h3. For HTTP/1
   * TLS connections, client_context is used which does not advertise h2
   * support.
   */
  static SSL_CTX *h3_client_context;

  /** The client context to use for HTTP/3 connections.
   *
   * This is used per HTTP/3 connection so that ALPN advertises h3. For HTTP/1
   * TLS connections, client_context is used which does not advertise h2
   * support.
   */
  static SSL_CTX *h3_server_context;

  /// The system status code. This is set to non-zero if problems are detected.
  static int *process_exit_code;
};
